version: '1.0'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teashop
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5433/teashop
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

volumes:
  pgdata:
